CREATE TABLE users (
	id BIGINT NOT NULL,
	age INTEGER,
	cash DOUBLE PRECISION NOT NULL,
	lastName VARCHAR(255),
	name VARCHAR(255),
	password VARCHAR(255),
	profilePhoto VARCHAR(255),
	username VARCHAR(255),
	PRIMARY KEY (id)
)